#define LED_DATA_PIN 2  
#define NUM_LEDS 300
#define NUM_ROWS 5
#define ROW_LENGTH 60
#define LED_FLASH_SPEED 500 
 
#define DELAY_REDRAW 0
#define REDRAW_DELAY_MS 15
#define INITIAL_CANVAS_COLOR CRGB::BlueViolet
#define DEFAULT_BRIGHTNESS 15

#define WIFI_CONNECTION_RETRY_DELAY 500

// Debugging
#define PRINT_CANVAS_BUILD 0
#define PRINT_CANVAS_DRAW_LOOP 0
#define PRINT_CANVAS_FILL 0
#define PRINT_SERVER_REQUESTS 0
#define PRINT_SERVER_PARAMS 1


